name: build

on:
  pull_request:
  push:
    branch:
      - master

jobs:
  build-ocaml:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        ocaml-compiler:
          - 4.08.x
          - 4.13.x
        package:
          - decoders-bencode
          - decoders-cbor
          - decoders-ezjsonm
          - decoders-ezxmlm
          - decoders-jsonm
          - decoders-msgpck
          - decoders-sexplib
          - decoders-yojson
        exclude:
          # To cut down the number of jobs, only run windows/macos with recent
          # compiler.
          - os: macos-latest
            ocaml-compiler: 4.08.x
          - os: windows-latest
            ocaml-compiler: 4.08.x


    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-depext-flags: --with-test

      - run: opam install ./decoders.opam "./${{ matrix.package }}.opam" --with-test

  build-node:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - 14.x

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build
      - run: npm test
